### ISSUE TITLE
Error running lineintersect.py on ArcMap 10.7.1

### ISSUE THREAD

**Issue by BenjiDa** [ethoms-usgs/Cross-Section#12]
Error running lineintersect.py on ArcMap 10.7.1

"line 304, in <module>
    arcpy.CreateRoutes_lr(xsecLayer, 'ORIG_FID', mLine, 'LENGTH', '#', '#', cp)

<class 'arcgisscripting.ExecuteError'>: ERROR 999999: Error executing function.
The table was not found. [A4_line.shp_m]
Could not create the output feature class
The table name is invalid.
The table was not found. [A4_line.shp_m]
Failed to execute (CreateRoutes)."

**Comment by ethoms-usgs** [comment]
I think I have it fixed. I only worked with GDB feature classes during development, never shapefiles. The method for determining the output name from the input resulted in the .shp extension being part of the name. Download and try that script again.

**Comment by BenjiDa** [comment]
Thanks, I just ran it successfully from a GDB!  If you did want to work it out for shapefiles, I ran it again and it seems to hang on something else, perhaps the table item names?

"lineintersect.py", line 197, in transferAtts
    arcpy.AddJoin_management(lName, parentKey, joinTable, childKey)

<class 'arcgisscripting.ExecuteError'>: Failed to execute. Parameters are not valid.
ERROR 000728: Field FID_A3_poly2line.shp does not exist within table
Failed to execute (AddJoin).

  File "C:\Users\Name\Cross-Section-master\GeologicCrossSectionTbx\scripts\lineintersect.py", line 363, in <module>
    transferAtts(xInterFeats, linesLayer, 'FID_' + trueName , linesIDF, xInterFeatsAtts)

<type 'exceptions.SystemError'>: "

**Comment by ethoms-usgs** [comment]
Bah! Ok, my first attempt to scrub the extension was not very robust; trying to be too elegant. After changes, I just ran the tool with shapefile inputs and it ran correctly. 

Probably have the same bug in other tools, but I am going to close this.
