### ISSUE TITLE
Map points to cross section points- Beta error

### ISSUE THREAD

**Issue by BenjiDa** [ethoms-usgs/Cross-Section#13]
Thanks for these tools ethoms-usgs!  I am trying to run the "Map points to cross section points- Beta" tool and it is erroring with the message here.  Wondering if there is a work around. Everything is in a GDB and in the same projection. 
Thanks for any insight. 

"
Traceback (most recent call last):
  File "C:\Users\...Tools\GIS_tools\Cross-Section-master\GeologicCrossSectionTbx\scripts\points2XsecView.py", line 212, in <module>
    arcpy.SelectLayerByLocation_management(ptLayer, 'WITHIN_A_DISTANCE', mLine, buff)
  File "c:\arcgis\desktop10.7\arcpy\arcpy\management.py", line 7890, in SelectLayerByLocation
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000368: Invalid input data.
Failed to execute (SelectLayerByLocation).
"

**Comment by BenjiDa** [comment]
Was able to get it to work, by selecting layers rather than pointing directly at feature classes in the GDB.

**Comment by ethoms-usgs** [comment]
Ok, I will still try to take a look at this.
