### ISSUE TITLE
Lines to surface Tool doesn't account for gaps in rastrer surface

### ISSUE THREAD

**Issue by acroskrey** [ethoms-usgs/Cross-Section#2]
Hi!
Thanks for updating this tool and making it public!

I would like to say that I ran the "Lines to surface profiles" tool on a surface topography DEM and the "Borehole locations to borehole sticks tool" and they appear to have worked great.  

The next thing I attempted was to add the surface profiles of buried formation tops and bottoms from rasters surfaces we interpolated from well log points. This may not be an intended use of the "Lines to surface profiles" tool. The lines look like they plotted along the Y axxis of the cross section correctly but not so much along the X axis.  Some of the formations are not continuous and instead of spacing out the breaks in the formation contact line along the X axis the lines produced are abutted to each other and all start all the way to the left.  As an example I have attached the same cross section three times.  One image was created by a co-worker in ViewLog, one was created in the trial version of Strater, and then the third is only partially created using tools from this toolbox.  Do you see in the first two examples how the green Cretaceous unit should be in two patches and the contacts are drawn right after the other in the third? I thought I could just edit this by making points along the topographic surface making the extend of the Cretaceous units and then sliding the lines over but I haven't been able to get the "Line intersections to cross-section features" tool to run.

Thoughts?
Andrea

![pva_xsection_f](https://cloud.githubusercontent.com/assets/9828087/5172615/07bff804-73e7-11e4-854d-0046c5e76ea0.png)
![strater_xsection_f](https://cloud.githubusercontent.com/assets/9828087/5172630/343685ba-73e7-11e4-8524-4202f902fb7c.png)
![usgstool_xsection_f_with_gap_issue](https://cloud.githubusercontent.com/assets/9828087/5172640/4ff5336e-73e7-11e4-858a-5a7e9b3e79aa.jpg)

**Comment by AlvaroMCMC** [comment]
Hi , acroskey , I am trying to do a topographic section from a Dem with specific scales in vertical and horizontal... , can you write me the steps for doing that..thank you in advance...

**Comment by acroskrey** [comment]
Sorry! I haven't done this for over 1.5 years. I just used ethoms-usgs's ArcTool, which you can download from this site. I'm guessing, since it has been too long for me to remember, there is an option in the toolsets to set vertical exaggeration and that is what I think you are asking about. Unless you mean the scale you would like for print and that would be a simple cartographic fix in ArcMap layout view. If you are having trouble with the tool, you should ask a specific question about the tool. Good luck!

**Comment by AlvaroMCMC** [comment]
That's what I have , a line and a Dem.
![captura](https://cloud.githubusercontent.com/assets/21317475/18063334/266a1d66-6df0-11e6-9fb6-66320e43669b.PNG)

![captura3](https://cloud.githubusercontent.com/assets/21317475/18063479/af2b6c36-6df0-11e6-9b9d-1e0a6a5813a0.PNG)
![captura4](https://cloud.githubusercontent.com/assets/21317475/18063480/b20aab38-6df0-11e6-9cb1-dc5f49a3f008.PNG)

At the end nothing show up.. what am I doing wrong?

**Comment by acroskrey** [comment]
Add the new feature you created (profile7.shp) to the GIS viewer of your choice.

**Comment by AlvaroMCMC** [comment]
Which one do you recommend ? Can I do that in Arcgis?

**Comment by acroskrey** [comment]
yep
