### ISSUE TITLE
Trying to make a cross-section with the demo material

### ISSUE THREAD

**Issue by baymag** [ethoms-usgs/Cross-Section#3]
Hi Evan,

I am trying to make a cross-section from polyline SectionA in the demo cross-section layer you provided. I can't seem to get the parameters right and was wondering if you could give me some guidance as to where I am going wrong? I have attached the pictures of all 3 steps that I'm doing.

![step 1](https://cloud.githubusercontent.com/assets/10833910/6026639/a919907c-ab99-11e4-827a-20b1cafec483.PNG)
![step 2](https://cloud.githubusercontent.com/assets/10833910/6026640/aa497462-ab99-11e4-8c60-faab24842a4b.PNG)
![step 3](https://cloud.githubusercontent.com/assets/10833910/6026646/be5ae936-ab99-11e4-9e49-32eb9739d7ae.PNG)

Thanks!

Brody
.

**Comment by evanthoms** [comment]
I just updated the python script behind that tool. You can download it separately:
(https://github.com/evanthoms/Cross-Section/blob/master/GeologicCrossSectionTbx/scripts/points2XsecView.py) or in the master zip download from the main page. 

If you want to download just the new file, go the address above, right-click on the Raw button, and choose 'Save link as', browse to the \scripts folder of the toolbox, and save it there, overwriting the older file.

You found a bug where points that were not representing orientation data were, nonetheless, being processed as orientation data. Lacking strike and dip fields, the script was failing. 

I don't know if it's my scripting or the arcpy update cursor I am using or what, but when 500 m is used as a search radius, you get over 400 points which was taking a very long time to process. Much slower than I think it should be. It might help to reduce the number of points in the feature class before processing by either extracting a sub set or using a definition filter on the layer. In my successful run I used a search radius of 50 and the results didn't take too long to run.

Also, when you select a value for DEM, be sure to select the DEM, not the hillshade.

**Comment by baymag** [comment]
I downloaded your new file and tried it, I think I am still having the same problem. I assume it's something I'm doing wrong so I will tell you what I have done: 

1) I selected one cross section polygon from the cross section layer and made it an individual layer (Just by opening the attribute table of "Cross Sections" --> Selecting the first line --> Selection --> Create layer from selected features)
![step 1a](https://cloud.githubusercontent.com/assets/10833910/6043659/099361e2-ac4b-11e4-8df6-121301a483b5.PNG)
![step 2a](https://cloud.githubusercontent.com/assets/10833910/6043661/09a61724-ac4b-11e4-8285-33b3c8188317.PNG)
![step 3a](https://cloud.githubusercontent.com/assets/10833910/6043662/09b5165c-ac4b-11e4-8ca0-b9c76a5a17c5.PNG)
![step 4a](https://cloud.githubusercontent.com/assets/10833910/6043660/09a29414-ac4b-11e4-976a-83a0e19505b7.PNG)



.

2) Selected points in close proximity to the cross section and made them into a layer (Selection --> Create layer from selected features --> Then I exported it to a shape file because it didn't seem to want to work when I entered it into the "Points Layer" field . I started editing and created a strike and dip field where I entered random strikes and dips for each point.

3) Ran the "Map points to cross-section points - beta" Tool (I will attach pictures again of those steps)

**Comment by evanthoms** [comment]
Whoops, sorry about that Brody. When I ran the tool I didn't get the error you got. I got another one, got distracted, and fixed that one (I hope).  I just now tracked down the error you got, made an edit, and had a successful run. Try  replacing points2xsecView.py again

**Comment by baymag** [comment]
Oh no worries! Hmmm I tried downloading it again today and when I ran it I
encountered a different error but I think it was due to the cross
section shapefile that I had exported, at least that's what it said in the
error messages. I tried again with a Cross Section Selection layer and got
the same error as I did 3 days ago. I have a feeling I downloaded the
points2xsecView.py link that you had updated 3 days ago instead of the one
you debugged yesterday.  Would you mind sending me a link to your most
recent copy so I can try again?

Thanks for your help Evan, if you get tired of trying to help me work
through this I definitely understand, so no worries if you don't get around
to it.

Brody

**Comment by evanthoms** [comment]
Darn, another apology on my part. My changes yesterday didn't sync with
github. I just confirmed that the .py script that is on github
(
https://github.com/evanthoms/Cross-Section/blob/master/GeologicCrossSectionTbx/scripts/points2XsecView.py
)
is the one that ran successfully for me, so try it again



On Fri, Feb 6, 2015 at 11:20 AM, baymag <notifications@github.com> wrote:

> Oh no worries! Hmmm I tried downloading it again today and when I ran it I
> encountered a different error but I think it was due to the cross
> section shapefile that I had exported, at least that's what it said in the
> error messages. I tried again with a Cross Section Selection layer and got
> the same error as I did 3 days ago. I have a feeling I downloaded the
> points2xsecView.py link that you had updated 3 days ago instead of the one
> you debugged yesterday. Would you mind sending me a link to your most
> recent copy so I can try again?
>
> Thanks for your help Evan, if you get tired of trying to help me work
> through this I definitely understand, so no worries if you don't get around
> to it.
>
> Brody
>
> On Thu, Feb 5, 2015 at 1:26 PM, evanthoms <notifications@github.com>
> wrote:
>
> > Whoops, sorry about that Brody. When I ran the tool I didn't get the
> error
> > you got. I got another one, got distracted, and fixed that one (I hope).
> I
> > just now tracked down the error you got, made an edit, and had a
> successful
> > run. Try replacing points2xsecView.py again
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/evanthoms/Cross-Section/issues/3#issuecomment-73120115>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evanthoms/Cross-Section/issues/3#issuecomment-73305572>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by baymag** [comment]
I think I must still be doing something wrong, however your updated version seems like it is a lot closer to working for me. I'm not sure if it's because I don't have a license of some type? I used the same parameters as in my last message, but got a different error this time.
![step 1b](https://cloud.githubusercontent.com/assets/10833910/6135174/ae895de6-b123-11e4-84f3-7af65c1ce2ea.PNG)

**Comment by evanthoms** [comment]
Ah, it appears that you don't have ArcGIS Desktop Advanced.

The function the script is calling DeleteIdentical in the Management
toolbox, is only available with that level of licensing.

The documentation for that tool is here:
http://resources.arcgis.com/en/help/main/10.1/index.html#//001700000054000000

If you do have the license for Advanced, I am not sure how you enable it.

I just updated the python file again to make an exception and pass over
that line if it fails to run so be aware that you may end up with multiple
coincident points in the final output and you will have to manually edit
them out.

Evan






On Tue, Feb 10, 2015 at 10:53 AM, baymag <notifications@github.com> wrote:

> I think I must still be doing something wrong, however your updated
> version seems like it is a lot closer to working for me. I'm not sure if
> it's because I don't have a license of some type? I used the same
> parameters as in my last message, but got a different error this time.
> [image: step 1b]
> <https://cloud.githubusercontent.com/assets/10833910/6135174/ae895de6-b123-11e4-84f3-7af65c1ce2ea.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evanthoms/Cross-Section/issues/3#issuecomment-73771037>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by baymag** [comment]
Yes you are correct Evan, unfortunately I only have ArcGIS Desktop Basic. I ran your updated script and I made it all the way to line 389 before I got an error, so I think I am really close to getting this to work. However, please don't feel obliged to help me out with this because I don't like wasting your time with my constant questions. I'm not sure why I keep getting errors and you do not, perhaps it's because I don't have an Advanced license?  
![step 1c](https://cloud.githubusercontent.com/assets/10833910/6156877/4d97676c-b1fa-11e4-8358-f70a965a6a1c.PNG)

I have attached a picture of the error I ran into today, but no worries if you don't have time to help me out.

Brody

**Comment by evanthoms** [comment]
Ok Brody, try again. It looks like you may not have specified an output
feature class and the code, as written, allowed that but then failed when
it needed a name to write to.

But you needn't download the new script file if you don't want to. The only
difference is a test for whether there is an output - a new feature class
to be created or an existing one to which new features are to be appended.

You are, indeed, close!

Evan

On Wed, Feb 11, 2015 at 12:30 PM, baymag <notifications@github.com> wrote:

> Yes you are correct Evan, unfortunately I only have ArcGIS Desktop Basic.
> I ran your updated script and I made it all the way to line 389 before I
> got an error, so I think I am really close to getting this to work.
> However, please don't feel obliged to help me out with this because I don't
> like wasting your time with my constant questions. I'm not sure why I keep
> getting errors and you do not, perhaps it's because I don't have an
> Advanced license?
>
> [image: step 1c]
> <https://cloud.githubusercontent.com/assets/10833910/6156877/4d97676c-b1fa-11e4-8358-f70a965a6a1c.PNG>
>
> I have attached a picture of the error I ran into today, but no worries if
> you don't have time to help me out.
>
> Brody
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evanthoms/Cross-Section/issues/3#issuecomment-73968809>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by baymag** [comment]
Ok, this morning I tried what you said and it worked! I ended up appending it to an existing feature class, in this case "cross_ sections" under the GEOLOGY main folder (it didn't seem to work for me when I tried to Create a new Feature Class, but I didn't really know what I was doing so I think I was trying to create a new shapefile possibly?). However, my problem now is that I couldn't figure out how to view the Cross Section that the script generated, would you mind explaining that to me? 

Thanks,
Brody

**Comment by evanthoms** [comment]
Great!
It could be that the tool will not make new shapefiles. I never tested
against shapefiles. If you set the output location to be a feature class in
a geodatabase, it should work. Make sure the feature class is going into a
feature dataset where the coordinate system is 'unknown' or not in a
feature dataset at all.

To see the features that were created make a new data frame in your map
document and move the layer there. If you are asking your question for the
reason I think you are, the reason you don't see your cross section
features is because at the end of the tool processing, the layer is added
to the map data frame, unless another data frame was chosen in the
parameter form, and Arc assumes that the coordinate system of the new
feature class is the same as the map. They are in the map, but off near
the origin of the coordinate system of the map data frame. If you
right-click on the cross section features and chose 'zoom to layer', you
should see the features being displayed. But those features aren't using
real-world map coordinates, so it doesn't make sense to look at them in
that frame anyway.

Make a new data frame called Cross Section and keep your features there.

Try that,
Evan

On Thu, Feb 12, 2015 at 11:13 AM, baymag <notifications@github.com> wrote:

> Ok, this morning I tried what you said and it worked! I ended up appending
> it to an existing feature class, in this case "cross_ sections" under the
> GEOLOGY main folder (it didn't seem to work for me when I tried to Create a
> new Feature Class, but I didn't really know what I was doing so I think I
> was trying to create a new shapefile possibly?). However, my problem now is
> that I couldn't figure out how to view the Cross Section that the script
> generated, would you mind explaining that to me?
>
> Thanks,
> Brody
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evanthoms/Cross-Section/issues/3#issuecomment-74143721>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by baymag** [comment]
Hi Evan,

I understand what you're saying, thanks for breaking it down for me. Honestly I think this is the first time I've ever used Feature Classes and Geodatabases. What I did was I went into ArcCatalog and I created a new geodatabase which I called "Cross Section Trial", in that geodatabase I created a new feature dataset which I named the same and in there I created a Feature Class where the coordinate system was 'unknown', under "Type of features stored in this feature class" I selected polygons (I also created another feature class where I chose "Type of features stored in this feature class" to be points). When I ran the script, I was able to view the Feature Class with points, but not the one with polygons. I then moved that feature class into my new data frame "Cross Sections". 

Would you mind taking a look at the picture of my result to see if this was what I was supposed to get? I have a feeling I did something a little funky.
![step 1d](https://cloud.githubusercontent.com/assets/10833910/6194183/11b6de54-b37f-11e4-9bf0-dce0e3308cd6.PNG)


Thanks!
Brody

**Comment by evanthoms** [comment]
Hi Brody,

Those points are symbolized using a so-called layer file (LYR extension)
that is in the \docs folder of the GeologicCrossSectionTbx folder
(structureTicks.lyr). They are symbols that can be rotated according to
apparent dip if you have structural data. If you don't need the tails on
the points, all you have to do is change the symbology in the layer
properties to a plain point.

Do you even have any features in the polygons cross section feature class
yet? None of the tools will make polygons in the cross section view from
map view data. Those would all be created by you as you interpret the
subsurface.

Evan

On Fri, Feb 13, 2015 at 10:52 AM, baymag <notifications@github.com> wrote:

> Hi Evan,
>
> I understand what you're saying, thanks for breaking it down for me.
> Honestly I think this is the first time I've ever used Feature Classes and
> Geodatabases. What I did was I went into ArcCatalog and I created a new
> geodatabase which I called "Cross Section Trial", in that geodatabase I
> created a new feature dataset which I named the same and in there I created
> a Feature Class where the coordinate system was 'unknown', under "Type of
> features stored in this feature class" I selected polygons (I also created
> another feature class where I chose "Type of features stored in this
> feature class" to be points). When I ran the script, I was able to view the
> Feature Class with points, but not the one with polygons. I then moved that
> feature class into my new data frame "Cross Sections".
>
> Would you mind taking a look at the picture of my result to see if this
> was what I was supposed to get? I have a feeling I did something a little
> funky.
> [image: step 1d]
> <https://cloud.githubusercontent.com/assets/10833910/6194183/11b6de54-b37f-11e4-9bf0-dce0e3308cd6.PNG>
>
> Thanks!
> Brody
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evanthoms/Cross-Section/issues/3#issuecomment-74315683>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by baymag** [comment]
Oh ok! I understand. So I guess my question now is: how can I use this to construct a cross section? I am so sorry for my lack of knowledge in this subject. 

Attached is a picture of my attribute table for the Points feature class. My polygons feature class does not contain any attributes.
![attribute table](https://cloud.githubusercontent.com/assets/10833910/6194791/ca71b8f6-b384-11e4-9676-6d7033448552.PNG)

**Comment by evanthoms** [comment]
Ah, so you appended the points to an existing point feature class? Your
target feature class doesn't have the same fields that your map-view points
feature class does, actually it appears you didn't add any.

The append option is not really made for the first time run through a tool.
It's really there so that after you have made a cross-section feature class
from map-view features that you can add to the collection on a second,
third, or whatever run.

If you run through the tool and specify the place and name for the creation
of a new feature class, all of the attributes of the original point fc will
be copied over.

On Fri, Feb 13, 2015 at 11:33 AM, baymag <notifications@github.com> wrote:

> Oh ok! I understand. So I guess my question now is: how can I use this to
> construct a cross section? I am so sorry for my lack of knowledge in this
> subject.
>
> Attached is a picture of my attribute table for the Points feature class.
> My polygons feature class does not contain any attributes.
> [image: attribute table]
> <https://cloud.githubusercontent.com/assets/10833910/6194791/ca71b8f6-b384-11e4-9676-6d7033448552.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evanthoms/Cross-Section/issues/3#issuecomment-74322078>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by baymag** [comment]
Ok that makes sense! 

I am trying to create a new feature class right now but I seem to be getting an error saying that my "output feature class does not exist or is not supported". The feature class I am trying to create I have named "Trial" and I am trying to save it in the "SeattleGeology.gdb" folder that you supplied with the demo material. Would you mind taking a look to see if I am making a mistake in that step? I have attached pictures of most of my steps, hopefully that will help identify my problem. 

Thanks Evan!
![feature class problem 1](https://cloud.githubusercontent.com/assets/10833910/6215494/72c820c2-b5be-11e4-9e98-684d72ef523b.PNG)
![feature class problem 2](https://cloud.githubusercontent.com/assets/10833910/6215496/72e32020-b5be-11e4-8743-03ccf6f6e88c.PNG)
![feature class problem 3](https://cloud.githubusercontent.com/assets/10833910/6215495/72cefc4e-b5be-11e4-80a5-01a2f01ec82d.PNG)
![feature class problem 4](https://cloud.githubusercontent.com/assets/10833910/6215492/72ad0832-b5be-11e4-842d-38f0a0114a7c.PNG)
![feature class problem 5](https://cloud.githubusercontent.com/assets/10833910/6215493/72bf16da-b5be-11e4-89d1-200af7c79109.PNG)

**Comment by evanthoms** [comment]
Hi Brody,
I think I know what's going on. It's weird that part of the path my default
gdb is in the path to your default gdb. That variable was stored with the
MXD, which I had never realized before.

In ArcMap go to File (on the top main menu) > Map Document Properties.
Near the bottom is a place where you can browse to a Default.gdb. It
probably reads C:\Users\ethoms\Documents\ArcGIS\Default.gdb right now so
set it to a geodatabase on your computer. There is probably one at
C:\Users\brody\Documents\ArcGIS\Default.gdb.

I am not sure how much consolation this is for all the problems you've come
up against, but I have to thank you for helping find them! You are helping
to make the project better.

Evan



On Mon, Feb 16, 2015 at 7:36 AM, baymag <notifications@github.com> wrote:

> Ok that makes sense!
>
> I am trying to create a new feature class right now but I seem to be
> getting an error saying that my "output feature class does not exist or is
> not supported". The feature class I am trying to create I have named
> "Trial" and I am trying to save it in the "SeattleGeology.gdb" folder that
> you supplied with the demo material. Would you mind taking a look to see if
> I am making a mistake in that step? I have attached pictures of most of my
> steps, hopefully that will help identify my problem.
>
> Thanks Evan!
> [image: feature class problem 1]
> <https://cloud.githubusercontent.com/assets/10833910/6215494/72c820c2-b5be-11e4-9e98-684d72ef523b.PNG>
> [image: feature class problem 2]
> <https://cloud.githubusercontent.com/assets/10833910/6215496/72e32020-b5be-11e4-8743-03ccf6f6e88c.PNG>
> [image: feature class problem 3]
> <https://cloud.githubusercontent.com/assets/10833910/6215495/72cefc4e-b5be-11e4-80a5-01a2f01ec82d.PNG>
> [image: feature class problem 4]
> <https://cloud.githubusercontent.com/assets/10833910/6215492/72ad0832-b5be-11e4-842d-38f0a0114a7c.PNG>
> [image: feature class problem 5]
> <https://cloud.githubusercontent.com/assets/10833910/6215493/72bf16da-b5be-11e4-89d1-200af7c79109.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evanthoms/Cross-Section/issues/3#issuecomment-74535873>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by baymag** [comment]
It's no problem at all! I feel bad for not being able to figure out some of this stuff on my own. I took Computer Science last year but unfortunately I was never very good with Python. Although I think I understand most of your code which is surprising.

I opened my Map Document Properties and the Default.gdb was set to: C:\Users\Brody\Documents\ArcGIS\Default.gdb already. I tried to change it to: C:\Users\ethoms\Documents\ArcGIS\Default.gdb which also came up with the same error.

I will keep playing around with it and see if I can get something to work for me. 

Brody

**Comment by evanthoms** [comment]
Weird.
You mean there is C:\Users\ethoms folder on your machine? There shouldn't
be.

Can you actually browse to either of those addresses in ArcCatalog and find
a .gdb there?

On Mon, Feb 16, 2015 at 12:38 PM, baymag <notifications@github.com> wrote:

> It's no problem at all! I feel bad for not being able to figure out some
> of this stuff on my own. I took Computer Science last year but
> unfortunately I was never very good with Python. Although I think I
> understand most of your code which is surprising.
>
> I opened my Map Document Properties and the Default.gdb was set to:
> C:\Users\Brody\Documents\ArcGIS\Default.gdb already. I tried to change it
> to: C:\Users\ethoms\Documents\ArcGIS\Default.gdb which also came up with
> the same error.
>
> I will keep playing around with it and see if I can get something to work
> for me.
>
> Brody
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evanthoms/Cross-Section/issues/3#issuecomment-74576275>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by baymag** [comment]
Sorry that was really confusing of me! No, there is not a C:\Users\ethoms folder on my computer. I just copied and pasted: C:\Users\ethoms\Documents\ArcGIS\Default.gdb into the map document properties for the Default.gdb to see if it would work, and of course it didn't because that folder does not exist on my computer. 

I will let you know when I get to work tomorrow morning, but I believe I can browse to the C:\Users\Brody\Documents\ArcGIS\Default.gdb.

**Comment by baymag** [comment]
I just checked and I can browse in ArcCatalog to the C:\Users\Brody\Documents\ArcGIS\Default.gdb folder, but not to the C:\Users\ethoms\Documents\ArcGIS\Default.gdb
