### ISSUE TITLE
How can i add all Cross-Section-master Scripts in arcgis gis toolbox and set parameter in and run the tool 

### ISSUE THREAD

**Issue by megis28** [ethoms-usgs/Cross-Section#4]
Plz step by step guide me to how can I install the all python scripts in  arcgis 10 Toolbox 
Because I add the scripts in newly created under GeologicCrossSectionTbx. After adding the scripts how can I define script parameters   and run the scripts file plz guide me because I have not software background skill

**Comment by evanthoms** [comment]
Please first review the instructions at:
https://github.com/evanthoms/Cross-Section for installation of the toolbox. The file called readme.txt which is included in the zip file also has the instructions. If something is not clear, is misleading, or still does not work, then write back with details.

thanks,
Evan
