### ISSUE TITLE
Error - Map points to Cross Section Points

### ISSUE THREAD

**Issue by pkumar1977** [ethoms-usgs/Cross-Section#5]
Hi,

I am working on demo data provided along with the Cross Section master tool. During execution of Map points to Cross Section points tool, error is shown as in the screenshot attached. I am using ArcGIS 10.3 Advanced version. I don't know where I am making the mistake. Please help me out!!

![mappoints](https://cloud.githubusercontent.com/assets/19687352/15709362/00e5b24a-280d-11e6-9100-27f878e1b108.JPG)

Thanks and Regards,
Praveen

**Comment by ethoms-usgs** [comment]
Hi Praveen,
I just ran the tool with the demo data from the SeattleGeology.gdb:

[image: Inline image 2]

And it worked fine with no errors.

Could you send me a screen shot of the Fields tab from the Feature Class
Properties or list of the fields in xsA_map_points_events?

Evan

On Wed, Jun 1, 2016 at 4:26 AM, pkumar1977 <notifications@github.com> wrote:

> Hi,
>
> I am working on demo data provided along with the Cross Section master
> tool. During execution of Map points to Cross Section points tool, error is
> shown as in the screenshot attached. I am using ArcGIS 10.3 Advanced
> version. I don't know where I am making the mistake. Please help me out!!
>
> [image: mappoints]
> <https://cloud.githubusercontent.com/assets/19687352/15709362/00e5b24a-280d-11e6-9100-27f878e1b108.JPG>
>
> Thanks and Regards,
> Praveen
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ethoms-usgs/Cross-Section/issues/5>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AFIJO-nztwrsvp1qS-PTENLCZtaWw75Jks5qHXpegaJpZM4IrfWo>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by pkumar1977** [comment]
Dear Ivan,

Attached screenshots for your reference.

Praveen

![mappoints-input](https://cloud.githubusercontent.com/assets/19687352/15733724/7d436542-2891-11e6-8718-bc25670cdae8.JPG)
![xsa_mappointsevents_table](https://cloud.githubusercontent.com/assets/19687352/15733723/7d435b38-2891-11e6-9635-6493fb409bd3.JPG)

**Comment by ethoms-usgs** [comment]
Hi Praveen,
The problem might be that 'structure_100k' is nested within the GEOLOGY
group layer in your map. This is a problem a few users have found and I
haven't moved the code that fixes it into all scripts. The tool doesn't get
the right name for the layer if it's nested within a group layer.
Try taking it out, running the tool, and get back to me.

Evan

On Wed, Jun 1, 2016 at 8:14 PM, pkumar1977 <notifications@github.com> wrote:

> Dear Ivan,
>
> Attached screenshots for your reference.
>
> Praveen
>
> [image: mappoints-input]
> <https://cloud.githubusercontent.com/assets/19687352/15733724/7d436542-2891-11e6-8718-bc25670cdae8.JPG>
> [image: xsa_mappointsevents_table]
> <https://cloud.githubusercontent.com/assets/19687352/15733723/7d435b38-2891-11e6-9635-6493fb409bd3.JPG>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ethoms-usgs/Cross-Section/issues/5#issuecomment-223191201>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFIJOzLANAiW8vVzbcRBl8SB_0JxX3_cks5qHliMgaJpZM4IrfWo>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by pkumar1977** [comment]
Hi Evan,

I moved 'structure_100k' layer from geology group and ran the tool. Still I am getting similar error. But  when I worked with my own data, the tool is working fine.

Praveen

**Comment by ethoms-usgs** [comment]
Excellent! Glad to hear that. Obviously, I don't know why 'structure_100k'
isn't working, but that's not the important data, yours is!

Evan

On Sat, Jun 4, 2016 at 9:07 PM, pkumar1977 <notifications@github.com> wrote:

> Hi Evan,
>
> I moved 'structure_100k' layer from geology group and ran the tool. Still
> I am getting similar error. But when I worked with my own data, the tool is
> working fine.
>
> Praveen
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ethoms-usgs/Cross-Section/issues/5#issuecomment-223793557>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFIJO2Z8QORa2OQ2yPR_-NlIUHtP0HJfks5qIlmqgaJpZM4IrfWo>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov

**Comment by pkumar1977** [comment]
Hi Evan,

Thanks again for your support and providing the tool.

Regards,
Praveen
