### ISSUE TITLE
Cross-section - modified code to address multiple surface rasters

### ISSUE THREAD

**Issue by mrobinson9** [ethoms-usgs/Cross-Section#6]
Andrea Croskrey helped me modify your "lines to surface profiles" to process multiple raster surfaces for a specific application of your code.  Results as shown below:
![lipan_xs_b_rev1](https://cloud.githubusercontent.com/assets/21082596/20803097/b074a1ae-b7b3-11e6-9a4a-d418cf533a40.jpg)

code used:
[LipanXsec.py.txt](https://github.com/ethoms-usgs/Cross-Section/files/625243/LipanXsec.py.txt)

Thanks for making this available
M.C. Robinson

**Comment by ethoms-usgs** [comment]
Very nice. Glad you could make use of the tool!
